### ISSUE TITLE
Container logger should honor log levels

### ISSUE THREAD

**Issue by slemrmartin** [ManageIQ/manageiq-loggers#18]
I want to start serious discussion about hardcoded default DEBUG severity for loggers.
https://github.com/ManageIQ/manageiq-loggers/blob/master/lib/manageiq/loggers/container.rb#L13

What's the reason? 
Meaning of debug logs are logs for development purpose -> it means they should NOT be written to containers and Kibana. 

What's an alternative for real debug logs? 
1) puts 
2) implementing `logger.i_really_want_debug_log()` ...?
3) if it has some reason for ManageIQ, ok, but it shouldn't be used for c.r.c.

cc @carbonin @gtanzillo

**Comment by carbonin** [comment]
The reasoning was that debug doesn't typically apply only to developers, but when you might want additional information in production for diagnosing a problem. Since changing the log level would require a container re-deploy (which might fix any problems you're seeing) we decided to always log at the highest verbosity level to ensure that everything that we could possibly need to diagnose an issue was captured.

Given that most container environments have a log aggregator (like kibana) it should be trivial to filter out the debug messages if you don't need the extra information.

I guess I could see making it configurable in case you have a particularly verbose application and don't want debug logs in production, but I would still suggest the default to be "debug" for the container logger.

**Comment by slemrmartin** [comment]
I got the re-deploy reason, that's true. 
It changes meaning of debug severity at all, but ok

**Comment by Fryguy** [comment]
I'm reopening this issue.  We continually run into cases where we explicitly don't want verbose logging, mostly around trying to cut down the volume of logging, but also in cases of bugs such as https://github.com/ManageIQ/manageiq-ui-classic/issues/7689
